[paths]
code_base_path = '/path/to/src/code' #insert the path of the directory you want to monitor
snapshot_path = '/path/to/src/code/dirSnapshot.p' #don't remove dirSnapshot.p!
gitignore_path = '/path/to/.gitignore' #provide the path to the .gitignore file
log_file_path = '/path/to/src/code/logs.log' #provide the path to your logs file


[observer]
files_to_observe = [
	'.py',       
	'.js',        
	'.java',      
	'.php',       
	'.rs',        
	'.html',      
	'.c',         
	'.cs',        
	'.md',        
	'.css',
	'.toml'        
]


[pinecone]
api_key = 'your-pinecone-api-key-here'
code-index_name = 'error-assistant-index'

[pinecone.code_namespace]
name = 'code-namespace'
top-k = 10

[agent]
hf-token = 'your-hf-token-here'