[paths]
code_base_path = '/home/tambascomarco35/error-assistant-mk3' #insert the path of the directory you want to monitor
snapshot_path = '/home/tambascomarco35/error-assistant-mk3/dirSnapshot.p' #don't remove dirSnapshot.p!
gitignore_path = '/home/tambascomarco35/error-assistant-mk3/.gitignore' #provide the path to the .gitignore file
log_file_path = '/home/tambascomarco35/error-assistant-mk3/logs.log' #provide the path to your logs file
env_path = '/home/tambascomarco35/error-assistant-mk3/env'


[observer]
files_to_observe = [
	'.py',       
	'.js',        
	'.java',      
	'.php',       
	'.rs',        
	'.html',      
	'.c',         
	'.cs',        
	'.md',        
	'.css',
	'.toml'        
]


[pinecone]
api_key = 'pcsk_6DgLEo_UmisTQWTNcSdsVWRZuGKrs642LfcH9MfdP8dzT9bmwzgBy1EyocU2CjutQyWjHi'
code-index_name = 'error-assistant-index'

[pinecone.code_namespace]
name = 'code-namespace'
top-k = 10

[agent]
hf-token = 'hf_pSSbpddgDuGfybyCOEgbQmwXnVUfsxkcHvhf_pSSbpddgDuGfybyCOEgbQmwXnVUfsxkcHv'