[paths]
code_base_path = '/home/marco/Projects/error-assistant' #insert the path of the directory you want to monitor
snapshot_path = '/home/marco/Projects/error-assistant/dirSnapshot.p' #don't remove dirSnapshot.p!
gitignore_path = '/home/marco/Projects/error-assistant/.gitignore' #provide the path to the .gitignore file
log_file_path = '/home/marco/Projects/error-assistant/logs.log' #provide the path to your logs file


[observer]
files_to_observe = [
	'.py',       
	'.js',        
	'.java',      
	'.php',       
	'.rs',        
	'.html',      
	'.c',         
	'.cs',        
	'.md',        
	'.css',
	'.toml'        
]


[pinecone]
api_key = 'pcsk_583DX1_37naR8wQjQBG2ZpTBqMTm5Ffv1T45w3KUDrM382a79oEUdwsGFjeXMbY9NcyaaC'
code-index_name = 'error-assistant-index'

[pinecone.code_namespace]
name = 'code-namespace'
top-k = 10
