[paths]
code_base_path = '/home/tambascomarco35/error-assistant-mk3/src/error_assistant' #insert the path of the directory you want to monitor
snapshot_path = '/home/tambascomarco35/error-assistant-mk3/src/error_assistant/dirSnapshot.p'
gitignore_path = '/home/tambascomarco35/error-assistant-mk3/.gitignore'
log_file_path = '/home/tambascomarco35/error-assistant-mk3/logs.log'


[observer]
files_to_observe = [
	'.py',       
	'.js',        
	'.java',      
	'.php',       
	'.rs',        
	'.html',      
	'.c',         
	'.cs',        
	'.md',        
	'.css',
	'.toml'        
]


[pinecone]
api_key = 'pcsk_4L4ZZj_7MTGh52jKUBr7rGtUY15Bc7eXv7owp5GWsrB99JcGfd4qEcYyTjTZjER1Qyu6kw'
code-index_name = 'error-assistant-index'

[pinecone.code_namespace]
name = 'code-namespace'
top-k = 10

[agent]
hf-token = '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'
