[paths]
code_base_path = '.'

[paths.ignores]
directories = ['env', '__pycache__', '.git', '.gitignore', '.mypy_cache', '.pytest_cache']
files = ['.log', '.pyc']

[pinecone]
api_key = 'your-api-key'
code-index_name = 'error-assistant-index'  

[pinecone.code-namespace]
name = 'code-namespace'
top-k = 10

[agent]
hf-token = 'your_hf_token'